/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AlertsRouteImport } from "./routes/alerts"
import { Route as AuditRouteImport } from "./routes/audit"
import { Route as CashRouteImport } from "./routes/cash"
import { Route as CounterRouteImport } from "./routes/counter"
import { Route as CustomersRouteImport } from "./routes/customers"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as DevicesRouteImport } from "./routes/devices"
import { Route as DueRouteImport } from "./routes/due"
import { Route as ExpensesRouteImport } from "./routes/expenses"
import { Route as HelpRouteImport } from "./routes/help"
import { Route as KdsRouteImport } from "./routes/kds"
import { Route as MenuRouteImport } from "./routes/menu"
import { Route as MoreRouteImport } from "./routes/more"
import { Route as OutletRouteImport } from "./routes/outlet"
import { Route as OutletsRouteImport } from "./routes/outlets"
import { Route as PrintersRouteImport } from "./routes/printers"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as QrOrdersRouteImport } from "./routes/qr-orders"
import { Route as QueueRouteImport } from "./routes/queue"
import { Route as ReservationsRouteImport } from "./routes/reservations"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as StaffRouteImport } from "./routes/staff"
import { Route as StatusRouteImport } from "./routes/status"
import { Route as SubscriptionRouteImport } from "./routes/subscription"
import { Route as TablesRouteImport } from "./routes/tables"
import { Route as TablesSetupRouteImport } from "./routes/tables-setup"
import { Route as TakeawayRouteImport } from "./routes/takeaway"
import { Route as TokensRouteImport } from "./routes/tokens"
import { Route as BillOrderIdRouteImport } from "./routes/bill.$orderId"
import { Route as EditBillOrderIdRouteImport } from "./routes/edit-bill.$orderId"
import { Route as OrderKeyRouteImport } from "./routes/order.$key"
import { Route as OrdersIndexRouteImport } from "./routes/orders.index"
import { Route as OrdersOrderIdRouteImport } from "./routes/orders.$orderId"
import { Route as ReportsIndexRouteImport } from "./routes/reports.index"
import { Route as ReportsReportIdRouteImport } from "./routes/reports.$reportId"
import { Route as StockIndexRouteImport } from "./routes/stock.index"
import { Route as StockSectionRouteImport } from "./routes/stock.$section"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: "/cash",
  path: "/cash",
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: "/counter",
  path: "/counter",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: "/devices",
  path: "/devices",
  getParentRoute: () => rootRouteImport,
} as any)
const DueRoute = DueRouteImport.update({
  id: "/due",
  path: "/due",
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: "/expenses",
  path: "/expenses",
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: "/help",
  path: "/help",
  getParentRoute: () => rootRouteImport,
} as any)
const KdsRoute = KdsRouteImport.update({
  id: "/kds",
  path: "/kds",
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: "/more",
  path: "/more",
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: "/outlet",
  path: "/outlet",
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsRoute = OutletsRouteImport.update({
  id: "/outlets",
  path: "/outlets",
  getParentRoute: () => rootRouteImport,
} as any)
const PrintersRoute = PrintersRouteImport.update({
  id: "/printers",
  path: "/printers",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const QrOrdersRoute = QrOrdersRouteImport.update({
  id: "/qr-orders",
  path: "/qr-orders",
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: "/queue",
  path: "/queue",
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: "/reservations",
  path: "/reservations",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: "/staff",
  path: "/staff",
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: "/status",
  path: "/status",
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: "/subscription",
  path: "/subscription",
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: "/tables",
  path: "/tables",
  getParentRoute: () => rootRouteImport,
} as any)
const TablesSetupRoute = TablesSetupRouteImport.update({
  id: "/tables-setup",
  path: "/tables-setup",
  getParentRoute: () => rootRouteImport,
} as any)
const TakeawayRoute = TakeawayRouteImport.update({
  id: "/takeaway",
  path: "/takeaway",
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: "/tokens",
  path: "/tokens",
  getParentRoute: () => rootRouteImport,
} as any)
const BillOrderIdRoute = BillOrderIdRouteImport.update({
  id: "/bill/$orderId",
  path: "/bill/$orderId",
  getParentRoute: () => rootRouteImport,
} as any)
const EditBillOrderIdRoute = EditBillOrderIdRouteImport.update({
  id: "/edit-bill/$orderId",
  path: "/edit-bill/$orderId",
  getParentRoute: () => rootRouteImport,
} as any)
const OrderKeyRoute = OrderKeyRouteImport.update({
  id: "/order/$key",
  path: "/order/$key",
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: "/reports/",
  path: "/reports/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: "/reports/$reportId",
  path: "/reports/$reportId",
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: "/stock/",
  path: "/stock/",
  getParentRoute: () => rootRouteImport,
} as any)
const StockSectionRoute = StockSectionRouteImport.update({
  id: "/stock/$section",
  path: "/stock/$section",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/audit": typeof AuditRoute
  "/cash": typeof CashRoute
  "/counter": typeof CounterRoute
  "/customers": typeof CustomersRoute
  "/dashboard": typeof DashboardRoute
  "/devices": typeof DevicesRoute
  "/due": typeof DueRoute
  "/expenses": typeof ExpensesRoute
  "/help": typeof HelpRoute
  "/kds": typeof KdsRoute
  "/menu": typeof MenuRoute
  "/more": typeof MoreRoute
  "/outlet": typeof OutletRoute
  "/outlets": typeof OutletsRoute
  "/printers": typeof PrintersRoute
  "/profile": typeof ProfileRoute
  "/qr-orders": typeof QrOrdersRoute
  "/queue": typeof QueueRoute
  "/reservations": typeof ReservationsRoute
  "/settings": typeof SettingsRoute
  "/staff": typeof StaffRoute
  "/status": typeof StatusRoute
  "/subscription": typeof SubscriptionRoute
  "/tables": typeof TablesRoute
  "/tables-setup": typeof TablesSetupRoute
  "/takeaway": typeof TakeawayRoute
  "/tokens": typeof TokensRoute
  "/bill/$orderId": typeof BillOrderIdRoute
  "/edit-bill/$orderId": typeof EditBillOrderIdRoute
  "/order/$key": typeof OrderKeyRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/reports/$reportId": typeof ReportsReportIdRoute
  "/stock/$section": typeof StockSectionRoute
  "/orders/": typeof OrdersIndexRoute
  "/reports/": typeof ReportsIndexRoute
  "/stock/": typeof StockIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/audit": typeof AuditRoute
  "/cash": typeof CashRoute
  "/counter": typeof CounterRoute
  "/customers": typeof CustomersRoute
  "/dashboard": typeof DashboardRoute
  "/devices": typeof DevicesRoute
  "/due": typeof DueRoute
  "/expenses": typeof ExpensesRoute
  "/help": typeof HelpRoute
  "/kds": typeof KdsRoute
  "/menu": typeof MenuRoute
  "/more": typeof MoreRoute
  "/outlet": typeof OutletRoute
  "/outlets": typeof OutletsRoute
  "/printers": typeof PrintersRoute
  "/profile": typeof ProfileRoute
  "/qr-orders": typeof QrOrdersRoute
  "/queue": typeof QueueRoute
  "/reservations": typeof ReservationsRoute
  "/settings": typeof SettingsRoute
  "/staff": typeof StaffRoute
  "/status": typeof StatusRoute
  "/subscription": typeof SubscriptionRoute
  "/tables": typeof TablesRoute
  "/tables-setup": typeof TablesSetupRoute
  "/takeaway": typeof TakeawayRoute
  "/tokens": typeof TokensRoute
  "/bill/$orderId": typeof BillOrderIdRoute
  "/edit-bill/$orderId": typeof EditBillOrderIdRoute
  "/order/$key": typeof OrderKeyRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/reports/$reportId": typeof ReportsReportIdRoute
  "/stock/$section": typeof StockSectionRoute
  "/orders": typeof OrdersIndexRoute
  "/reports": typeof ReportsIndexRoute
  "/stock": typeof StockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/audit": typeof AuditRoute
  "/cash": typeof CashRoute
  "/counter": typeof CounterRoute
  "/customers": typeof CustomersRoute
  "/dashboard": typeof DashboardRoute
  "/devices": typeof DevicesRoute
  "/due": typeof DueRoute
  "/expenses": typeof ExpensesRoute
  "/help": typeof HelpRoute
  "/kds": typeof KdsRoute
  "/menu": typeof MenuRoute
  "/more": typeof MoreRoute
  "/outlet": typeof OutletRoute
  "/outlets": typeof OutletsRoute
  "/printers": typeof PrintersRoute
  "/profile": typeof ProfileRoute
  "/qr-orders": typeof QrOrdersRoute
  "/queue": typeof QueueRoute
  "/reservations": typeof ReservationsRoute
  "/settings": typeof SettingsRoute
  "/staff": typeof StaffRoute
  "/status": typeof StatusRoute
  "/subscription": typeof SubscriptionRoute
  "/tables": typeof TablesRoute
  "/tables-setup": typeof TablesSetupRoute
  "/takeaway": typeof TakeawayRoute
  "/tokens": typeof TokensRoute
  "/bill/$orderId": typeof BillOrderIdRoute
  "/edit-bill/$orderId": typeof EditBillOrderIdRoute
  "/order/$key": typeof OrderKeyRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/reports/$reportId": typeof ReportsReportIdRoute
  "/stock/$section": typeof StockSectionRoute
  "/orders/": typeof OrdersIndexRoute
  "/reports/": typeof ReportsIndexRoute
  "/stock/": typeof StockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/alerts"
    | "/audit"
    | "/cash"
    | "/counter"
    | "/customers"
    | "/dashboard"
    | "/devices"
    | "/due"
    | "/expenses"
    | "/help"
    | "/kds"
    | "/menu"
    | "/more"
    | "/outlet"
    | "/outlets"
    | "/printers"
    | "/profile"
    | "/qr-orders"
    | "/queue"
    | "/reservations"
    | "/settings"
    | "/staff"
    | "/status"
    | "/subscription"
    | "/tables"
    | "/tables-setup"
    | "/takeaway"
    | "/tokens"
    | "/bill/$orderId"
    | "/edit-bill/$orderId"
    | "/order/$key"
    | "/orders/$orderId"
    | "/reports/$reportId"
    | "/stock/$section"
    | "/orders/"
    | "/reports/"
    | "/stock/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/alerts"
    | "/audit"
    | "/cash"
    | "/counter"
    | "/customers"
    | "/dashboard"
    | "/devices"
    | "/due"
    | "/expenses"
    | "/help"
    | "/kds"
    | "/menu"
    | "/more"
    | "/outlet"
    | "/outlets"
    | "/printers"
    | "/profile"
    | "/qr-orders"
    | "/queue"
    | "/reservations"
    | "/settings"
    | "/staff"
    | "/status"
    | "/subscription"
    | "/tables"
    | "/tables-setup"
    | "/takeaway"
    | "/tokens"
    | "/bill/$orderId"
    | "/edit-bill/$orderId"
    | "/order/$key"
    | "/orders/$orderId"
    | "/reports/$reportId"
    | "/stock/$section"
    | "/orders"
    | "/reports"
    | "/stock"
  id:
    | "__root__"
    | "/"
    | "/alerts"
    | "/audit"
    | "/cash"
    | "/counter"
    | "/customers"
    | "/dashboard"
    | "/devices"
    | "/due"
    | "/expenses"
    | "/help"
    | "/kds"
    | "/menu"
    | "/more"
    | "/outlet"
    | "/outlets"
    | "/printers"
    | "/profile"
    | "/qr-orders"
    | "/queue"
    | "/reservations"
    | "/settings"
    | "/staff"
    | "/status"
    | "/subscription"
    | "/tables"
    | "/tables-setup"
    | "/takeaway"
    | "/tokens"
    | "/bill/$orderId"
    | "/edit-bill/$orderId"
    | "/order/$key"
    | "/orders/$orderId"
    | "/reports/$reportId"
    | "/stock/$section"
    | "/orders/"
    | "/reports/"
    | "/stock/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  CashRoute: typeof CashRoute
  CounterRoute: typeof CounterRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  DueRoute: typeof DueRoute
  ExpensesRoute: typeof ExpensesRoute
  HelpRoute: typeof HelpRoute
  KdsRoute: typeof KdsRoute
  MenuRoute: typeof MenuRoute
  MoreRoute: typeof MoreRoute
  OutletRoute: typeof OutletRoute
  OutletsRoute: typeof OutletsRoute
  PrintersRoute: typeof PrintersRoute
  ProfileRoute: typeof ProfileRoute
  QrOrdersRoute: typeof QrOrdersRoute
  QueueRoute: typeof QueueRoute
  ReservationsRoute: typeof ReservationsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StatusRoute: typeof StatusRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TablesRoute: typeof TablesRoute
  TablesSetupRoute: typeof TablesSetupRoute
  TakeawayRoute: typeof TakeawayRoute
  TokensRoute: typeof TokensRoute
  BillOrderIdRoute: typeof BillOrderIdRoute
  EditBillOrderIdRoute: typeof EditBillOrderIdRoute
  OrderKeyRoute: typeof OrderKeyRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  StockSectionRoute: typeof StockSectionRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  StockIndexRoute: typeof StockIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/alerts": {
      id: "/alerts"
      path: "/alerts"
      fullPath: "/alerts"
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/audit": {
      id: "/audit"
      path: "/audit"
      fullPath: "/audit"
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cash": {
      id: "/cash"
      path: "/cash"
      fullPath: "/cash"
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/counter": {
      id: "/counter"
      path: "/counter"
      fullPath: "/counter"
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers": {
      id: "/customers"
      path: "/customers"
      fullPath: "/customers"
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/devices": {
      id: "/devices"
      path: "/devices"
      fullPath: "/devices"
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/due": {
      id: "/due"
      path: "/due"
      fullPath: "/due"
      preLoaderRoute: typeof DueRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/expenses": {
      id: "/expenses"
      path: "/expenses"
      fullPath: "/expenses"
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/help": {
      id: "/help"
      path: "/help"
      fullPath: "/help"
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/kds": {
      id: "/kds"
      path: "/kds"
      fullPath: "/kds"
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/menu": {
      id: "/menu"
      path: "/menu"
      fullPath: "/menu"
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/more": {
      id: "/more"
      path: "/more"
      fullPath: "/more"
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/outlet": {
      id: "/outlet"
      path: "/outlet"
      fullPath: "/outlet"
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/outlets": {
      id: "/outlets"
      path: "/outlets"
      fullPath: "/outlets"
      preLoaderRoute: typeof OutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/printers": {
      id: "/printers"
      path: "/printers"
      fullPath: "/printers"
      preLoaderRoute: typeof PrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/qr-orders": {
      id: "/qr-orders"
      path: "/qr-orders"
      fullPath: "/qr-orders"
      preLoaderRoute: typeof QrOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/queue": {
      id: "/queue"
      path: "/queue"
      fullPath: "/queue"
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reservations": {
      id: "/reservations"
      path: "/reservations"
      fullPath: "/reservations"
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/staff": {
      id: "/staff"
      path: "/staff"
      fullPath: "/staff"
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/status": {
      id: "/status"
      path: "/status"
      fullPath: "/status"
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/subscription": {
      id: "/subscription"
      path: "/subscription"
      fullPath: "/subscription"
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tables": {
      id: "/tables"
      path: "/tables"
      fullPath: "/tables"
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tables-setup": {
      id: "/tables-setup"
      path: "/tables-setup"
      fullPath: "/tables-setup"
      preLoaderRoute: typeof TablesSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/takeaway": {
      id: "/takeaway"
      path: "/takeaway"
      fullPath: "/takeaway"
      preLoaderRoute: typeof TakeawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tokens": {
      id: "/tokens"
      path: "/tokens"
      fullPath: "/tokens"
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bill/$orderId": {
      id: "/bill/$orderId"
      path: "/bill/$orderId"
      fullPath: "/bill/$orderId"
      preLoaderRoute: typeof BillOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/edit-bill/$orderId": {
      id: "/edit-bill/$orderId"
      path: "/edit-bill/$orderId"
      fullPath: "/edit-bill/$orderId"
      preLoaderRoute: typeof EditBillOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/order/$key": {
      id: "/order/$key"
      path: "/order/$key"
      fullPath: "/order/$key"
      preLoaderRoute: typeof OrderKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/orders/": {
      id: "/orders/"
      path: "/orders"
      fullPath: "/orders/"
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/orders/$orderId": {
      id: "/orders/$orderId"
      path: "/orders/$orderId"
      fullPath: "/orders/$orderId"
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reports/": {
      id: "/reports/"
      path: "/reports"
      fullPath: "/reports/"
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reports/$reportId": {
      id: "/reports/$reportId"
      path: "/reports/$reportId"
      fullPath: "/reports/$reportId"
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/stock/": {
      id: "/stock/"
      path: "/stock"
      fullPath: "/stock/"
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/stock/$section": {
      id: "/stock/$section"
      path: "/stock/$section"
      fullPath: "/stock/$section"
      preLoaderRoute: typeof StockSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  CashRoute: CashRoute,
  CounterRoute: CounterRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  DueRoute: DueRoute,
  ExpensesRoute: ExpensesRoute,
  HelpRoute: HelpRoute,
  KdsRoute: KdsRoute,
  MenuRoute: MenuRoute,
  MoreRoute: MoreRoute,
  OutletRoute: OutletRoute,
  OutletsRoute: OutletsRoute,
  PrintersRoute: PrintersRoute,
  ProfileRoute: ProfileRoute,
  QrOrdersRoute: QrOrdersRoute,
  QueueRoute: QueueRoute,
  ReservationsRoute: ReservationsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StatusRoute: StatusRoute,
  SubscriptionRoute: SubscriptionRoute,
  TablesRoute: TablesRoute,
  TablesSetupRoute: TablesSetupRoute,
  TakeawayRoute: TakeawayRoute,
  TokensRoute: TokensRoute,
  BillOrderIdRoute: BillOrderIdRoute,
  EditBillOrderIdRoute: EditBillOrderIdRoute,
  OrderKeyRoute: OrderKeyRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  StockSectionRoute: StockSectionRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  StockIndexRoute: StockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
